### ISSUE TITLE
slr_damages equal in m1 and m2

### ISSUE THREAD

**Issue by hforew** [rffscghg/MimiGIVE.jl#52]
Running the GIVE model for n = 2 trials yields identical slr_damages for m1 and m2. Is this expected? 

For mortality, energy and ag damages, for time > 2020, the values in model 1 and model 2 are different. 

[slr_damages.csv](https://github.com/user-attachments/files/16014272/slr_damages.csv)
[slr_damages.csv](https://github.com/user-attachments/files/16014278/slr_damages.csv)

**Comment by lrennels** [comment]
@hforew I apologize for the delay! Looking at these two files the values are not exactly the same, they do diverge, as one would expect since the difference would be undercounted marginal damages for sea level rise. One note is that these exported global sea level rise damages are exported in **billions of 2005 USD** -- depending which variables you are exporting in the `save_list` for energy and agriculture those may be in **2005 USD** (see comments within the model).

**Comment by hforew** [comment]
@lrennels Thank you for this detail.
