### ISSUE TITLE
Reconciling total damages and individual sectors

### ISSUE THREAD

**Issue by hforew** [rffscghg/MimiGIVE.jl#53]
For model 1 output, with n = 10,000, I am comparing the damages output across the following files from save_list: 

- slr_damages.csv
- DamageAggregator_cromar_mortality_damage.csv
- DamageAggregator_energy_damage.csv
- DamageAggregator_agriculture_damage.csv
- DamageAggregator_total_damage.csv

Importing these damage files into SQL, I then averaged across the 10,000 trials, grouping by year, yielding a single damage value per year. 

Next, I compared the sum of mortality, energy, agriculture, and slr damages to the total, which did not match. 

How can the values reported in DamageAggregator_total_damage.csv be reconciled with those in the individual sectors files?

Note, for the primary results, I successfully replicate the total SCC_CO2 of $185 for year = 2020 and 2.0% Ramsey

**Comment by hforew** [comment]
Note, for these five files, if I select year = 2021 and trialnum = 1, then the sum of mortality, energy, and agriculture damages equals the total damage (excluding slr).

**Comment by hforew** [comment]
Additionally, looking across all years and trials---without performing an average across trials---total damage appears to equal the sum of mortality, energy, and agriculture damages (excluding slr). is this as expected?

**Comment by lrennels** [comment]
Hi @hforew yes great question and I apologize for the delay.

This is expected, although of course admittedly unintuitive. The `total_damages` from the `DamageAggregator` will not include sea-level rise due to modeling details that force us to couple the sea-level module _after_ running the rest of the GIVE model. If you take a look at the code from that component, you will see there is no sea-level rise calculation.

Sea-level rise damages are not computed if you run
```
m = MimiGIVE.get_model()
run(m)
```
They are only computed when you run `compute_scc`, as they are run coupled on to the back-end. You can also fully couple them to a deterministic run using the code here: https://github.com/rffscghg/MimiGIVE.jl?tab=readme-ov-file#2b-append-offline-mimiciam-coupling

**Comment by lrennels** [comment]
Don't hesitate to reach out if you have any further questions about this!

**Comment by hforew** [comment]
@lrennels Thank you for this explanation.
