### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by austinrwg** [rffscghg/MimiGIVE.jl#72]
Hi!

If you can help me with this problem, then I would very much appreciate it: which variable(s) will allow me to replicate this graph, as shown below.

Specifically, the FaIR 1.6.2 solid black line.

<img width="548" alt="Screenshot 2024-11-25 100927" src="https://github.com/user-attachments/assets/6f2a71c4-0c84-43ab-be5d-c4f9ff02746b">

Thank you so much!

**Comment by lrennels** [comment]
Hi @austinrwg, to replicate the temperature impulse response graph above you will want the temperature anomaly variable from the FaIR climate module, which could for example use the variable `global_temperature_norm` in the `TempNorm_1850to1900` component, or since it's just the delta you could use `T` from the `temperature` component.
```
(:TempNorm_1850to1900, :global_temperature_norm), # Global surface temperature anomaly (K) from preinudstrial
# or
(:temperature, :T)
```
To replicate the graph you'd take the difference in temperature trajectories between the base run and the marginal run, which includes a pulse of carbon dioxide in the year 2030, and then normalize to pulse size and molecular mass as needed.

**Comment by austinrwg** [comment]
Thank you.

Why do temperature anomalies differ slightly between GIVE and DSCIM?

Although they follow the same trajectory and their values are extremely close, the numbers are still slightly different.

**Comment by lrennels** [comment]
I'm not sure I can reliably answer without more information on the current version of the DSCIM implementation and where it's run from? If the differences are small, then a few answers may include
- uncertainty due to the MCS -- even if they are using the same 2,237 parameter sets derived from AR6 the means may not match exactly
- different specifications or versions of the FaIR model -- we use version 1.6.2 matched to the settings and uncertain parameters of AR6 but there are quite a few versions of FaIR available in its original Python form

**Comment by austinrwg** [comment]
Thank you.

I just have one clarification to ask for this sentence: "To replicate the graph you'd take the difference in temperature trajectories between the base run and the marginal run, which includes a pulse of carbon dioxide in the year 2030, and then normalize to **pulse size** and **molecular mass** as needed."

I changed pulse_size to 1, but what would I need to change about the molecular mass?

Having pulse_size = 1 seems to do the job to replicate the graph.

**Comment by lrennels** [comment]
Hi @austinrwg, it sounds like you're good to go then.

That comment was just that especially when comparing temperature impulse responses between models I find that the two units conversions always worth double checking are magnitude of pulse size and molecular mass. 

For pulse size, you're right, the units for a pulse of carbon are Gt, so if you have `pulse_size = 1` you should be fine. For HFCs, for example, the baseline pulse size is in units of Mt, and for most of our social cost work we use a small pulse size like `pulse_size = 1e-4` so I just wanted to check what you were using.

And then sometimes those graphs are per Gt of _carbon dioxide_ instead of _carbon_, so the 44/12 conversion can be needed to get the y-axis to be what you want.

**Comment by lrennels** [comment]
@austinrwg I'll close this issue for now, as it seems resolved, but feel free to open a new issue with further questions!

**Comment by austinrwg** [comment]
Thank you!

**Comment by bryanparthum** [comment]
Hi @austinrwg, please see [here ](https://github.com/USEPA/scghg/blob/figures/EPA/code/figures/plot_temperature_anomaly.R)for replication code for that figure. 

As for the difference between DSCIM and GIVE temperature anomalies, @lrennels hit the nail on the head with the pulse size and chemistry conversions. Please see the [DSCIM User Manual](https://github.com/USEPA/scghg/blob/main/DSCIM/DSCIM_User_Manual.pdf) for the relevant pulse sizes.
